name: pilar
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.6
  image_picker: ^1.2.0
  permission_handler: ^11.3.0
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  lottie: ^3.1.2
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  http: ^1.1.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/images/history/
    # Logo untuk Splash
    - assets/images/Logo Icon Pilar.svg
    
    # Onboarding SVG
    - assets/images/Onboarding 1.svg
    - assets/images/Onboarding 2.svg
    - assets/images/Onboarding 3.svg
